log:
  level: debug
  disable_sentry: true

db:
  url: db_url

certificates_issuer:
  list:
    - address: contract_address
      name: contract_name
      from_block: block_to_start_from

certificates_fabric:
  list:
    - address: contract_address
      name: contract_name
      from_block: block_to_start_from

networks:
  list:
    - name: ethereum
      rpc_provider_ws_url: wss://...
      block_explorer_api_url: https://...
      block_explorer_api_key: api_key
      cert_integrator_address: contract_address
      wallet_private_key: private_key
    - name: polygon
      rpc_provider_ws_url: wss://...
      block_explorer_api_url: https://...
      block_explorer_api_key: api_key
      cert_integrator_address: contract_address
      wallet_private_key: private_key
    - name: q
      rpc_provider_ws_url: wss://...
      block_explorer_api_url: https://...
      block_explorer_api_key: api_key
      cert_integrator_address: contract_address
      wallet_private_key: private_key

timeouts:
  indexer: 30s
  sender:  30s
  cleaner: 30s

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: cert-integrator-svc
  service_port: 80